CREATE DATABASE vueblog;
USE vueblog;
CREATE TABLE m_user(
	id BIGINT(20) AUTO_INCREMENT,
	username VARCHAR(64) DEFAULT NULL,
	avatar VARCHAR(256) DEFAULT NULL,
	email VARCHAR(64) DEFAULT NULL,
	PASSWORD VARCHAR(64) DEFAULT NULL,
	STATUS INT(5) NOT NULL,
	created DATETIME DEFAULT NULL,
	last_login DATETIME DEFAULT NULL,
	PRIMARY KEY(id)
);
CREATE TABLE m_blog(
	id BIGINT(20) AUTO_INCREMENT,
	user_id BIGINT(20) NOT NULL,
	title VARCHAR(255) NOT NULL,
	DESCRIPTION VARCHAR(255) NOT NULL,
	content LONGTEXT,
	created DATETIME NOT NULL ON UPDATE CURRENT_TIMESTAMP,
	STATUS TINYINT(4) DEFAULT NULL,
	PRIMARY KEY(id)
)